{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nodejs-k8s-cicd.serviceAccountName" . }}
  labels:
{{ include "nodejs-k8s-cicd.labels" . | indent 4 }}
{{- end -}}
